// examples/react/src/pages/index.tsx
import React from 'react'
import { Link } from 'react-router-dom'

const index: React.FC = () => {
  return (
    <div>
      <p>index.vue</p>
      <Link to="/blog">
        blog
      </Link> |
      <Link to="/about">
        about
      </Link> |
      <Link to="/components">
        components
      </Link> |
      <Link to="/markdown">
        markdown
      </Link> |
      <Link to="/xxx">
        not exits
      </Link>
    </div>
  )
}

export default index

// examples/vue/src/pages/index.vue
<template>
  <div>
    <p>index.vue</p>
    <router-link to="/blog">
      blog
    </router-link> |
    <router-link to="/about">
      about
    </router-link> |
    <router-link to="/components">
      components
    </router-link> |
    <router-link to="/markdown">
      markdown
    </router-link> |
    <router-link to="/xxx">
      not exits
    </router-link>
  </div>
</template>

<route>
{
  name: "name-override",
  meta: {requiresAuth: false}
}
</route>
