// examples/solid/src/pages/index.tsx
import { Link } from '@solidjs/router'

export default function Index() {
  return (
    <div>
      <p>index.tsx</p>
      <Link href="/blog">
        blog
      </Link> |
      <Link href="/about">
        about
      </Link> |
      <Link href="/components">
        components
      </Link> |
      <Link href="/xxx/xxx">
        not exits
      </Link> |
      <Link href="/features/dashboard">
        features:dashboard
      </Link> |
      <Link href="/features/admin">
        features:admin
      </Link> |
      <Link href="/admin">
        admin
      </Link>
    </div>
  )
}

// examples/vue/src/pages/index.vue
<template>
  <div>
    <p>index.vue</p>
    <router-link to="/blog">
      blog
    </router-link> |
    <router-link to="/about">
      about
    </router-link> |
    <router-link to="/components">
      components
    </router-link> |
    <router-link to="/markdown">
      markdown
    </router-link> |
    <router-link to="/xxx">
      not exits
    </router-link> |
    <router-link to="/features/dashboard">
      features:dashboard
    </router-link> |
    <router-link to="/features/admin">
      features:admin
    </router-link> |
    <router-link to="/admin">
      admin
    </router-link>
  </div>
</template>

<route>
{
  name: "homepage",
  meta: {requiresAuth: false}
}
</route>
