// examples/vue-nuxt3/src/pages/about/[id].vue
<script setup lang="ts">
defineProps({
  id: String,
})
</script>

<template>
  <div>
    <div>
      about/[id].vue: {{ id }}
    </div>
    <router-link to="/about/1b234bk12b3/more">
      more deep
    </router-link>
    <router-view />
  </div>
</template>

<route>
{
  name: 'about-user-id',
  meta: {
    requiresAuth: true,
  },
}
</route>

// examples/solid-test/src/pages/blog/[id].tsx
import { useParams } from 'solid-app-router'

export default function Id() {
  const { id } = useParams<{id: string}>()
  return <>
    <div>
      <p>blog/[id].tsx: { id }</p>
      <p>
        {/* {{ $route }} */}
      </p>
    </div>
  </>
}

/* TODO
<route>
{
  name: 'blog-id',
  meta: {
    requiresAuth: false,
  },
}
</route>
*/
