// examples/solid-test/src/pages/about/[id].tsx
import { Link, Outlet, useParams } from 'solid-app-router'

export default function IdLayout() {
  const { id } = useParams<{id: string}>()
  return <>
    <div>
      <div>
      about/[id].tsx: { id }
      </div>
      <Link href="/about/1b234bk12b3/more">
        more deep
      </Link>
      <Outlet />
    </div>
  </>
}

/* TODO
<route>
{
  name: 'about-user-id',
  meta: {
    requiresAuth: true,
  },
}
</route>
*/

// examples/solid/src/pages/about/[id].tsx
import { useParams } from '@solidjs/router'
import type { ParentComponent } from 'solid-js'

const IdLayout: ParentComponent = ({ children }) => {
  const { id } = useParams<{ id: string }>()
  return (
    <div>
      <div>
        about/[id].tsx:
        {' '}
        { id }
      </div>
      <a href="/about/1b234bk12b3/more">
        more deep
      </a>
      {children}
    </div>
  )
}

export default IdLayout
