// examples/vue-nuxt3/src/pages/about/[id].vue
<script setup lang="ts">
defineProps({
  id: String,
})
</script>

<template>
  <div>
    <div>
      about/[id].vue: {{ id }}
    </div>
    <router-link to="/about/1b234bk12b3/more">
      more deep
    </router-link>
    <router-view />
  </div>
</template>

<route>
{
  name: 'about-user-id',
  meta: {
    requiresAuth: true,
  },
}
</route>

// examples/solid-test/src/pages/about/[id].tsx
import { Link, Outlet, useParams } from 'solid-app-router'

export default function IdLayout() {
  const { id } = useParams<{id: string}>()
  return <>
    <div>
      <div>
      about/[id].tsx: { id }
      </div>
      <Link href="/about/1b234bk12b3/more">
        more deep
      </Link>
      <Outlet />
    </div>
  </>
}

/* TODO
<route>
{
  name: 'about-user-id',
  meta: {
    requiresAuth: true,
  },
}
</route>
*/
